#!/usr/bin/env bash
#
# Builds the native ApproxMC dependency chain (CryptoMiniSat5, Arjun, SBVA,
# cadical/cadiback, ApproxMC) into third_party/install and generates the
# .cargo/config.toml rpath entry the crates need at link/run time.
#
# Usage:
#   scripts/setup-native.sh            # clone (if needed) + build + install
#   scripts/setup-native.sh --clean    # wipe third_party/ first, then rebuild
#
# System packages are NOT installed automatically; see the README.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THIRD_PARTY="${REPO_ROOT}/third_party"
SRC="${THIRD_PARTY}/approxmc"
BUILD="${SRC}/build"
INSTALL="${THIRD_PARTY}/install"
REPO_URL="${APPROXMC_REPO:-https://github.com/meelgroup/approxmc.git}"

if [[ "${1:-}" == "--clean" ]]; then
    echo ">> Removing ${THIRD_PARTY}"
    rm -rf "${THIRD_PARTY}"
fi

mkdir -p "${THIRD_PARTY}"

if [[ ! -d "${SRC}/.git" ]]; then
    echo ">> Cloning ApproxMC from ${REPO_URL}"
    git clone --depth 1 "${REPO_URL}" "${SRC}"
else
    echo ">> Reusing existing clone at ${SRC}"
fi

echo ">> Configuring (CMake, shared libs, FetchContent pulls the rest)"
cmake -S "${SRC}" -B "${BUILD}" -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DENABLE_TESTING=OFF \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DCMAKE_INSTALL_PREFIX="${INSTALL}"

echo ">> Building"
cmake --build "${BUILD}" -j"$(nproc)"

echo ">> Installing into ${INSTALL}"
cmake --install "${BUILD}"

# The shared libraries install to lib64 on this platform, lib on others.
LIBDIR="${INSTALL}/lib64"
[[ -d "${LIBDIR}" ]] || LIBDIR="${INSTALL}/lib"

echo ">> Writing ${REPO_ROOT}/.cargo/config.toml (rpath -> ${LIBDIR})"
mkdir -p "${REPO_ROOT}/.cargo"
cat > "${REPO_ROOT}/.cargo/config.toml" <<EOF
# Generated by scripts/setup-native.sh. Points binaries and tests at the
# in-tree ApproxMC install prefix. --disable-new-dtags makes the rpath
# transitive so indirectly-loaded libraries (libcryptominisat5, ...) resolve.
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C",
    "link-arg=-Wl,--disable-new-dtags",
    "-C",
    "link-arg=-Wl,-rpath,${LIBDIR}",
]
EOF

echo ">> Done. Now run: cargo test"
